
const allGames = [
    // Existing Corrected Games
    { "appId": "730", "name": "Counter-Strike 2", "videoId": "c80_n4yP4fM", "tags": ["FPS", "Shooter", "Multiplayer"], "descriptionKey": "desc_cs2" },
    { "appId": "570", "name": "Dota 2", "videoId": "0pL_cp6nDoY", "tags": ["MOBA", "Multiplayer", "Strategy"], "descriptionKey": "desc_dota2" },
    { "appId": "440", "name": "Team Fortress 2", "videoId": "N_p5i_d_a-o", "tags": ["Hero Shooter", "Free to Play", "Multiplayer"], "descriptionKey": "desc_tf2" },
    { "appId": "1091500", "name": "Cyberpunk 2077", "videoId": "8X2kIfS6fb8", "tags": ["RPG", "Open World", "Sci-fi"], "descriptionKey": "desc_cyberpunk" },
    { "appId": "271590", "name": "Grand Theft Auto V", "videoId": "QkkoHAzjnUs", "tags": ["Open World", "Action", "Multiplayer"], "descriptionKey": "desc_gta5" },
    { "appId": "1172470", "name": "Apex Legends", "videoId": "z4p2NIg24-A", "tags": ["Battle Royale", "Hero Shooter", "Free to Play"], "descriptionKey": "desc_apex" },
    { "appId": "578080", "name": "PUBG: BATTLEGROUNDS", "videoId": "vC23a9i9sIY", "tags": ["Battle Royale", "Shooter", "Multiplayer"], "descriptionKey": "desc_pubg" },
    { "appId": "359550", "name": "Tom Clancy's Rainbow Six Siege", "videoId": "6wlvYh0h63k", "tags": ["Tactical Shooter", "FPS", "Multiplayer"], "descriptionKey": "desc_r6" },
    { "appId": "1086940", "name": "Baldur's Gate 3", "videoId": "6dK3439362o", "tags": ["RPG", "CRPG", "D&D"], "descriptionKey": "desc_bg3" },
    { "appId": "252950", "name": "Rocket League", "videoId": "SgSX3gOrj60", "tags": ["Sports", "Cars", "Multiplayer"], "descriptionKey": "desc_rocket" },
    // Newly Added Games
    { "appId": "105600", "name": "Terraria", "videoId": "w7uOhFTrrq0", "tags": ["Sandbox", "Survival", "2D"], "descriptionKey": "desc_terraria" },
    { "appId": "413150", "name": "Stardew Valley", "videoId": "ot7uXNQskhs", "tags": ["Farming Sim", "RPG", "Life Sim"], "descriptionKey": "desc_stardew" },
    { "appId": "1145360", "name": "Hades", "videoId": "mD8x5g21j2E", "tags": ["Roguelike", "Action", "Mythology"], "descriptionKey": "desc_hades" },
    { "appId": "1245620", "name": "ELDEN RING", "videoId": "E3Huy2cdeLc", "tags": ["Souls-like", "RPG", "Open World"], "descriptionKey": "desc_eldenring" },
    { "appId": "892970", "name": "Valheim", "videoId": "BSrju9J0Lzs", "tags": ["Survival", "Sandbox", "Viking"], "descriptionKey": "desc_valheim" },
    { "appId": "620", "name": "Portal 2", "videoId": "tax4e4hBBZc", "tags": ["Puzzle", "Co-op", "Sci-fi"], "descriptionKey": "desc_portal2" },
    { "appId": "292030", "name": "The Witcher 3: Wild Hunt", "videoId": "c0i88t0Kacs", "tags": ["RPG", "Open World", "Fantasy"], "descriptionKey": "desc_witcher3" },
    { "appId": "220", "name": "Half-Life 2", "videoId": "g_3B0o_2A2k", "tags": ["FPS", "Action", "Sci-fi"], "descriptionKey": "desc_hl2" },
    { "appId": "427520", "name": "Factorio", "videoId": "DR01YdFtWFI", "tags": ["Automation", "Base Building", "Simulation"], "descriptionKey": "desc_factorio" },
    { "appId": "230410", "name": "Warframe", "videoId": "Runa50pGkVA", "tags": ["Looter Shooter", "Action", "Free to Play"], "descriptionKey": "desc_warframe" },
    { "appId": "374320", "name": "DARK SOULS III", "videoId": "_zDZYrIUgKE", "tags": ["Souls-like", "Action", "RPG"], "descriptionKey": "desc_ds3" },
    { "appId": "489830", "name": "The Elder Scrolls V: Skyrim", "videoId": "PjqsYzBrP-M", "tags": ["RPG", "Open World", "Fantasy"], "descriptionKey": "desc_skyrim" },
    { "appId": "1623730", "name": "Palworld", "videoId": "W_V_G8p4g48", "tags": ["Creature-Collector", "Survival", "Open World"], "descriptionKey": "desc_palworld" },
    { "appId": "2054970", "name": "Lethal Company", "videoId": "Ehshg1-z3-E", "tags": ["Co-op", "Horror", "First-Person"], "descriptionKey": "desc_lethalcompany" },
    { "appId": "553850", "name": "HELLDIVERS 2", "videoId": "oD_0c_03-ys", "tags": ["Co-op", "Shooter", "Action"], "descriptionKey": "desc_helldivers2" },
    { "appId": "1203620", "name": "Enshrouded", "videoId": "v4_h-6fS_a8", "tags": ["Survival", "RPG", "Building"], "descriptionKey": "desc_enshrouded" },
    { "appId": "431960", "name": "Wallpaper Engine", "videoId": "wgt3_i5DR3Y", "tags": ["Utility", "Design", "Customization"], "descriptionKey": "desc_wallpaperengine" },
    { "appId": "391540", "name": "Undertale", "videoId": "1Hojv0m3TqA", "tags": ["RPG", "Indie", "Pixel Graphics"], "descriptionKey": "desc_undertale" },
    { "appId": "252490", "name": "Rust", "videoId": "LmLQy8iL3v4", "tags": ["Survival", "PvP", "Building"], "descriptionKey": "desc_rust" },
    { "appId": "1938090", "name": "Call of Duty", "videoId": "5k8n24I2fP8", "tags": ["FPS", "Multiplayer", "Action"], "descriptionKey": "desc_cod" },
    { "appId": "782330", "name": "DOOM Eternal", "videoId": "2HOClc6Svg4", "tags": ["FPS", "Action", "Demons"], "descriptionKey": "desc_doom" },
    { "appId": "601150", "name": "Devil May Cry 5", "videoId": "8k6Q3g-gtYQ", "tags": ["Action", "Hack and Slash", "Character Action"], "descriptionKey": "desc_dmc5" }
];

const translations = {
    "en": {
        "title": "Steam Game Reviews",
        "hotGamesTitle": "🔥 Hot Right Now",
        "allGamesTitle": "🎮 All Games",
        "searchInputPlaceholder": "Search games...",
        "refreshButton": "Show Me Other Games",
        "watchTrailer": "Watch Trailer",
        // Descriptions
        "desc_cs2": "Counter-Strike 2 is the largest technical leap forward in Counter-Strike's history, ensuring new features and updates for years to come.",
        "desc_dota2": "Every day, millions of players worldwide enter battle as one of over a hundred Dota Heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover.",
        "desc_tf2": "Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!",
        "desc_cyberpunk": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.",
        "desc_gta5": "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond.",
        "desc_apex": "A free-to-play hero shooter where legendary characters with powerful abilities team up to battle for fame and fortune on the fringes of the Frontier.",
        "desc_pubg": "Land, loot, and outwit your opponents to become the last player left standing in a thrilling game experience full of unexpected, adrenaline-pumping moments.",
        "desc_r6": "Engage in a brand-new style of assault using an unrivaled level of destruction and gadgetry. In Rainbow Six Siege, you will face intense close-quarters combat, high lethality, tactical decision-making, team play, and explosive action.",
        "desc_bg3": "Gather your party, and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.",
        "desc_rocket": "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition.",
        "desc_terraria": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. The world is your canvas and the ground itself is your paint.",
        "desc_stardew": "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.",
        "desc_hades": "Defy the god of the dead as you hack and slash out of the Underworld of Greek myth in this rogue-like dungeon crawler from the creators of Bastion and Transistor.",
        "desc_eldenring": "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        "desc_valheim": "A brutal exploration and survival game for 1-10 players, set in a procedurally-generated purgatory inspired by viking culture. Battle, build, and conquer your way to a saga worthy of Odin’s patronage!",
        "desc_portal2": "The 'Perpetual Testing Initiative' has been expanded to allow you to design co-op puzzles for you and your friends!",
        "desc_witcher3": "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.",
        "desc_hl2": "1998. HALF-LIFE sends a shock through the game industry with its combination of pounding action and continuous, immersive storytelling. Valve’s debut title wins more than 50 game-of-the-year awards on its way to being named 'Best PC Game Ever' by PC Gamer, and launches a franchise with more than eight million retail units sold worldwide.",
        "desc_factorio": "Factorio is a game in which you build and maintain factories. You will be mining resources, researching technologies, building infrastructure, automating production, and fighting enemies.",
        "desc_warframe": "Confront warring factions throughout a sprawling interplanetary system as you follow the guidance of the mysterious Lotus and level up your Warframe, build an Arsenal of destructive firepower, and realize your true potential across massive open worlds in this thrilling, third-person combat experience.",
        "desc_ds3": "As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments. Players will be immersed into a world of epic atmosphere and darkness through faster gameplay and amplified combat intensity.",
        "desc_skyrim": "The next chapter in the highly anticipated Elder Scrolls saga arrives from the makers of the 2006 and 2008 Games of the Year, Bethesda Game Studios. Skyrim reimagines and revolutionizes the open-world fantasy epic, bringing to life a complete virtual world open for you to explore any way you choose.",
        "desc_palworld": "Fight, farm, build and work alongside mysterious creatures called 'Pals' in this completely new multiplayer, open world survival and crafting game!",
        "desc_lethalcompany": "A co-op horror about scavenging abandoned moons for scrap. You are a contracted worker for the Company. Your job is to collect scrap from abandoned, industrialized moons to meet the Company's profit quota.",
        "desc_helldivers2": "The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter.",
        "desc_enshrouded": "You are the last hope of a dying people. Survive the encroaching blight, and reclaim the lost beauty of your kingdom. Venture into a vast world, vanquish punishing bosses, build epic halls and forge your path in this co-op survival action RPG for up to 16 players.",
        "desc_wallpaperengine": "Use stunning live wallpapers on your desktop. Animate your own images to create new wallpapers or import videos/websites and share them on the Steam Workshop!",
        "desc_undertale": "Welcome to UNDERTALE. In this RPG, you control a human who falls underground into the world of monsters. Now you must find your way out... or stay trapped forever.",
        "desc_rust": "The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.",
        "desc_cod": "Call of Duty® returns to its roots with Call of Duty®: WWII—a breathtaking experience that redefines World War II for a new gaming generation.",
        "desc_doom": "Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity.",
        "desc_dmc5": "The ultimate Devil Hunter is back in style, in the game action fans have been waiting for."
    },
    "ko": {
        "title": "스팀 게임 리뷰",
        "hotGamesTitle": "🔥 지금 뜨는 게임",
        "allGamesTitle": "🎮 모든 게임",
        "searchInputPlaceholder": "게임 검색...",
        "refreshButton": "다른 게임 보기",
        "watchTrailer": "트레일러 보기",
        // Descriptions
        "desc_cs2": "Counter-Strike 2는 Counter-Strike 역사상 가장 큰 기술적 도약으로, 앞으로 몇 년 동안 새로운 기능과 업데이트를 보장합니다.",
        "desc_dota2": "매일 전 세계 수백만 명의 플레이어가 100명이 넘는 도타 영웅 중 하나가 되어 전투에 참여합니다. 10시간을 플레이했든 1,000시간을 플레이했든, 항상 새로운 것을 발견할 수 있습니다.",
        "desc_tf2": "9개의 독특한 클래스는 다양한 전술적 능력과 개성을 제공합니다. 새로운 게임 모드, 맵, 장비, 그리고 가장 중요한 모자로 끊임없이 업데이트됩니다!",
        "desc_cyberpunk": "Cyberpunk 2077은 거대 도시 나이트 시티를 배경으로 하는 오픈 월드, 액션 어드벤처 RPG입니다. 당신은 사이버펑크 용병이 되어 생사를 건 싸움에 휘말리게 됩니다.",
        "desc_gta5": "PC용 Grand Theft Auto V는 플레이어에게 수상 경력에 빛나는 로스 산토스와 블레인 카운티의 세계를 최대 4k 이상의 해상도로 탐험할 수 있는 옵션을 제공합니다.",
        "desc_apex": "전설적인 캐릭터들이 강력한 능력을 가지고 팀을 이루어 프론티어의 변방에서 명예와 부를 위해 싸우는 무료 플레이 영웅 슈팅 게임입니다.",
        "desc_pubg": "예상치 못한 아드레날린이 솟구치는 순간으로 가득한 스릴 넘치는 게임 경험 속에서 마지막 생존자가 되기 위해 착륙하고, 약탈하고, 상대를 압도하세요.",
        "desc_r6": "타의 추종을 불허하는 수준의 파괴와 장비를 사용하여 새로운 스타일의 공격에 참여하십시오. Rainbow Six Siege에서는 치열한 근접 전투, 높은 치사율, 전술적 의사 결정, 팀 플레이 및 폭발적인 액션에 직면하게 됩니다.",
        "desc_bg3": "파티를 모아 동료애와 배신, 희생과 생존, 그리고 절대적인 힘의 유혹에 대한 이야기 속에서 포가튼 렐름으로 돌아가십시오.",
        "desc_rocket": "Rocket League는 이해하기 쉬운 컨트롤과 유동적이고 물리 기반 경쟁을 갖춘 아케이드 스타일 축구와 차량 난동의 강력한 하이브리드입니다.",
        "desc_terraria": "파고, 싸우고, 탐험하고, 건설하세요! 이 액션으로 가득 찬 어드벤처 게임에서는 불가능한 것이 없습니다. 세상은 당신의 캔버스이고 땅 자체가 당신의 물감입니다.",
        "desc_stardew": "당신은 Stardew Valley에 있는 할아버지의 오래된 농장을 물려받았습니다. 물려받은 도구와 약간의 동전으로 무장하고 새로운 삶을 시작합니다.",
        "desc_hades": "Bastion과 Transistor의 제작진이 만든 이 로그라이크 던전 크롤러에서 그리스 신화의 지하 세계를 해킹하고 베며 죽음의 신에게 도전하세요.",
        "desc_eldenring": "새로운 판타지 액션 RPG. 일어나라, 빛바랜 자여, 그리고 은총의 인도를 받아 엘든 링의 힘을 휘두르고 중간계의 엘든 군주가 되십시오.",
        "desc_valheim": "바이킹 문화에서 영감을 받은 절차적으로 생성된 연옥을 배경으로 하는 1-10인용 잔혹한 탐험 및 생존 게임입니다. 오딘의 후원에 합당한 사가를 향해 전투하고, 건설하고, 정복하세요!",
        "desc_portal2": "'영구 테스트 이니셔티브'가 확장되어 당신과 친구들을 위한 협동 퍼즐을 디자인할 수 있게 되었습니다!",
        "desc_witcher3": "북부 왕국 전역에서 전쟁이 계속되는 동안, 당신은 당신의 인생에서 가장 큰 계약을 맺습니다 — 세계의 모양을 바꿀 수 있는 살아있는 무기인 예언의 아이를 추적하는 것입니다.",
        "desc_hl2": "1998년. HALF-LIFE는 강렬한 액션과 지속적이고 몰입감 있는 스토리텔링의 조합으로 게임 산업에 충격을 주었습니다. Valve의 데뷔 타이틀은 PC Gamer에 의해 '역대 최고의 PC 게임'으로 선정되는 과정에서 50개 이상의 올해의 게임 상을 수상했으며, 전 세계적으로 800만 개 이상의 소매 유닛을 판매한 프랜차이즈를 시작했습니다.",
        "desc_factorio": "Factorio는 공장을 짓고 유지하는 게임입니다. 자원을 채굴하고, 기술을 연구하고, 인프라를 구축하고, 생산을 자동화하고, 적과 싸우게 됩니다.",
        "desc_warframe": "신비로운 로터스의 안내에 따라 광대한 행성 간 시스템에서 전쟁 중인 파벌에 맞서고, 워프레임의 레벨을 올리고, 파괴적인 화력의 무기고를 구축하고, 이 스릴 넘치는 3인칭 전투 경험에서 거대한 오픈 월드에서 진정한 잠재력을 실현하십시오.",
        "desc_ds3": "불이 꺼지고 세상이 폐허가 될 때, 더 거대한 적과 환경으로 가득 찬 우주로 여행을 떠나십시오. 플레이어는 더 빠른 게임 플레이와 증폭된 전투 강도를 통해 장대한 분위기와 어둠의 세계에 몰입하게 될 것입니다.",
        "desc_skyrim": "2006년과 2008년 올해의 게임을 만든 Bethesda Game Studios에서 매우 기대되는 Elder Scrolls 사가의 다음 장이 도착합니다. Skyrim은 오픈 월드 판타지 서사시를 재창조하고 혁신하여 원하는 방식으로 탐험할 수 있는 완전한 가상 세계에 생명을 불어넣습니다.",
        "desc_palworld": "이 완전히 새로운 멀티플레이어, 오픈 월드 서바이벌 및 제작 게임에서 'Pals'라는 신비한 생물과 함께 싸우고, 농사를 짓고, 건물을 짓고, 일하세요!",
        "desc_lethalcompany": "버려진 달에서 고철을 줍는 것에 대한 협동 공포. 당신은 회사의 계약직 근로자입니다. 당신의 임무는 버려진 산업화된 달에서 고철을 수집하여 회사의 이익 할당량을 충족하는 것입니다.",
        "desc_helldivers2": "은하계의 마지막 방어선. 헬다이버에 입대하여 빠르고, 광란적이며, 사나운 3인칭 슈팅 게임에서 적대적인 은하계 전역에서 자유를 위한 싸움에 동참하십시오.",
        "desc_enshrouded": "당신은 죽어가는 사람들의 마지막 희망입니다. 잠식하는 역병에서 살아남아 잃어버린 왕국의 아름다움을 되찾으세요. 최대 16인용 이 협동 서바이벌 액션 RPG에서 광대한 세계로 모험을 떠나고, 강력한 보스를 물리치고, 장대한 홀을 건설하고, 자신의 길을 개척하세요.",
        "desc_wallpaperengine": "바탕 화면에서 멋진 라이브 배경화면을 사용하세요. 자신의 이미지를 애니메이션하여 새로운 배경화면을 만들거나 비디오/웹사이트를 가져와 Steam 창작마당에서 공유하세요!",
        "desc_undertale": "UNDERTALE에 오신 것을 환영합니다. 이 RPG에서 당신은 지하로 떨어져 몬스터의 세계로 들어가는 인간을 조종합니다. 이제 당신은 출구를 찾아야 합니다... 아니면 영원히 갇히게 될 것입니다.",
        "desc_rust": "Rust의 유일한 목표는 생존하는 것입니다. 모든 것이 당신이 죽기를 원합니다 - 섬의 야생 동물과 다른 주민들, 환경, 다른 생존자들. 또 다른 밤을 버티기 위해 무엇이든 하십시오.",
        "desc_cod": "Call of Duty®가 Call of Duty®: WWII로 뿌리로 돌아옵니다—새로운 게임 세대를 위해 제2차 세계 대전을 재정의하는 숨막히는 경험.",
        "desc_doom": "지옥의 군대가 지구를 침공했습니다. 차원을 넘어 악마를 정복하고 인류의 최종 파괴를 막기 위한 장대한 싱글 플레이어 캠페인에서 슬레이어가 되십시오.",
        "desc_dmc5": "궁극의 데빌 헌터가 액션 팬들이 기다려온 게임에서 스타일리시하게 돌아왔습니다."
    }
};
