
const allGames = [
    { name: 'Counter-Strike 2', appId: 730, videoId: 'c80_g_m2_RA', tags: ['FPS', 'Shooter', 'Multiplayer', 'Competitive'], descriptionKey: 'cs2Desc' },
    { name: 'Dota 2', appId: 570, videoId: '-cSFPIwQp4s', tags: ['MOBA', 'Strategy', 'Free to Play'], descriptionKey: 'dota2Desc' },
    { name: 'PUBG: BATTLEGROUNDS', appId: 578080, videoId: '93h9a3_j2j0', tags: ['Battle Royale', 'Shooter', 'Multiplayer'], descriptionKey: 'pubgDesc' },
    { name: 'Apex Legends', appId: 1172470, videoId: 'o2Wf_1_1y5E', tags: ['Hero Shooter', 'Battle Royale', 'Free to Play'], descriptionKey: 'apexLegendsDesc' },
    { name: 'Grand Theft Auto V', appId: 271590, videoId: 'QkkoHAzjnUs', tags: ['Open World', 'Action', 'Multiplayer'], descriptionKey: 'gta5Desc' },
    { name: 'Stardew Valley', appId: 413150, videoId: 'ot7uXNQskhs', tags: ['Farming Sim', 'RPG', 'Life Sim'], descriptionKey: 'stardewValleyDesc' },
    { name: 'Tom Clancy'''s Rainbow Six Siege', appId: 359550, videoId: '6wlvYh0h63k', tags: ['Tactical', 'FPS', 'Multiplayer'], descriptionKey: 'rainbowSixSiegeDesc' },
    { name: 'Rust', appId: 252490, videoId: 'LGcECozNXEw', tags: ['Survival', 'PvP', 'Multiplayer'], descriptionKey: 'rustDesc' },
    { name: 'Warframe', appId: 230410, videoId: 'ZxB-aV2s6sU', tags: ['Looter Shooter', 'Action RPG', 'Free to Play'], descriptionKey: 'warframeDesc' },
    { name: 'Destiny 2', appId: 1085660, videoId: '8FHe3y_2i_Q', tags: ['Looter Shooter', 'FPS', 'Free to Play'], descriptionKey: 'destiny2Desc' },
    { name: 'Team Fortress 2', appId: 440, videoId: 'N1_qI-3S_0w', tags: ['Hero Shooter', 'Free to Play', 'Classic'], descriptionKey: 'tf2Desc' },
    { name: 'Sid Meier'''s Civilization VI', appId: 289070, videoId: '5KdE0p2z_t4', tags: ['4X', 'Turn-Based Strategy', 'Historical'], descriptionKey: 'civ6Desc' },
    { name: 'The Witcher 3: Wild Hunt', appId: 292030, videoId: 'c0i88t0Kacs', tags: ['Action RPG', 'Open World', 'Story Rich'], descriptionKey: 'witcher3Desc' },
    { name: 'Terraria', appId: 105600, videoId: 'w7uOhFTrrq0', tags: ['Sandbox', 'Adventure', '2D'], descriptionKey: 'terrariaDesc' },
    { name: 'Garry'''s Mod', appId: 4000, videoId: 'hpjV962DLws', tags: ['Sandbox', 'Physics', 'Multiplayer'], descriptionKey: 'gmodDesc' },
    { name: 'ARK: Survival Evolved', appId: 346110, videoId: 'aQM8Y-d6qUg', tags: ['Survival', 'Open World', 'Dinosaurs'], descriptionKey: 'arkDesc' },
    { name: 'Fallout 4', appId: 377160, videoId: 'GE2BkLqMef4', tags: ['Open World', 'RPG', 'Post-Apocalyptic'], descriptionKey: 'fallout4Desc' },
    { name: 'The Elder Scrolls V: Skyrim', appId: 489830, videoId: 'JSRtYpNRoN0', tags: ['Open World', 'RPG', 'Singleplayer'], descriptionKey: 'skyrimDesc' },
    { name: 'Among Us', appId: 945360, videoId: 'grdYIbf_2wE', tags: ['Social Deduction', 'Multiplayer', 'Party Game'], descriptionKey: 'amongUsDesc' },
    { name: 'Valheim', appId: 892970, videoId: 'BSrJRrls_0w', tags: ['Survival', 'Open World', 'Co-op', 'Viking'], descriptionKey: 'valheimDesc' },
    { name: 'Red Dead Redemption 2', appId: 1174180, videoId: 'eaW0tYpxLC0', tags: ['Open World', 'Action', 'Story Rich'], descriptionKey: 'rdr2Desc' },
    { name: 'Cyberpunk 2077', appId: 1091500, videoId: '8X2kIfS6fb8', tags: ['Action RPG', 'Open World', 'Sci-Fi'], descriptionKey: 'cyberpunk2077Desc' },
    { name: 'Elden Ring', appId: 1245620, videoId: 'E3Huy2cdih0', tags: ['Souls-like', 'Action RPG', 'Open World'], descriptionKey: 'eldenRingDesc' },
    { name: 'Baldur'''s Gate 3', appId: 1086940, videoId: '1T22pB-Mi5U', tags: ['CRPG', 'Turn-Based', 'Story Rich'], descriptionKey: 'baldursGate3Desc' },
    { name: 'HELLDIVERS 2', appId: 553850, videoId: 'wX-2g_G9Kz4', tags: ['Co-op', 'Shooter', 'Sci-Fi'], descriptionKey: 'helldivers2Desc' },
    { name: 'Lethal Company', appId: 1966720, videoId: '8v5O2-Lw_I8', tags: ['Co-op', 'Horror', 'Survival'], descriptionKey: 'lethalCompanyDesc' },
    { name: 'Palworld', appId: 1623730, videoId: 'W_2quIponmE', tags: ['Survival', 'Creature Collector', 'Open World'], descriptionKey: 'palworldDesc' },
    { name: 'Monster Hunter: World', appId: 582010, videoId: 'XP-VqK6iS6s', tags: ['Action RPG', 'Co-op', 'Open World'], descriptionKey: 'monsterHunterWorldDesc' },
    { name: 'Left 4 Dead 2', appId: 550, videoId: 'g4D21G_2T1g', tags: ['Co-op', 'Zombies', 'FPS', 'Action'], descriptionKey: 'left4Dead2Desc' },
    { name: 'Hades', appId: 1145360, videoId: '91t0ha9x0AE', tags: ['Action Roguelike', 'Indie', 'Mythology'], descriptionKey: 'hadesDesc' },
    { name: 'The Binding of Isaac: Rebirth', appId: 250900, videoId: 'brh_iC2KQiQ', tags: ['Roguelike', 'Dungeon Crawler', 'Indie'], descriptionKey: 'bindingOfIsaacDesc' },
    { name: 'Hollow Knight', appId: 367520, videoId: 'UAO2urG23S4', tags: ['Metroidvania', 'Platformer', 'Indie', 'Souls-like'], descriptionKey: 'hollowKnightDesc' },
    { name: 'Dead by Daylight', appId: 381210, videoId: 'J_uF_OKI_4k', tags: ['Horror', 'Survival', 'Multiplayer', 'Asymmetrical'], descriptionKey: 'deadByDaylightDesc' },
    { name: 'Phasmophobia', appId: 739630, videoId: 'sN2-a4VfT1E', tags: ['Horror', 'Co-op', 'VR', 'Psychological Horror'], descriptionKey: 'phasmophobiaDesc' },
    { name: 'Don'''t Starve Together', appId: 322330, videoId: 'bV1HcOf_v2A', tags: ['Survival', 'Co-op', 'Crafting', 'Indie'], descriptionKey: 'dontStarveTogetherDesc' },
    { name: 'Factorio', appId: 427520, videoId: 'KVvXv1Z6rws', tags: ['Automation', 'Base Building', 'Simulation', 'Strategy'], descriptionKey: 'factorioDesc' },
    { name: 'Slay the Spire', appId: 646570, videoId: 'C9wMC-2P04c', tags: ['Deckbuilder', 'Roguelike', 'Card Game', 'Strategy'], descriptionKey: 'slayTheSpireDesc' },
    { name: 'RimWorld', appId: 294100, videoId: '3tDrxO-w_6w', tags: ['Colony Sim', 'Survival', 'Base Building', 'Strategy'], descriptionKey: 'rimworldDesc' },
    { name: 'Subnautica', appId: 264710, videoId: 'Rz2SNm8VguE', tags: ['Survival', 'Open World', 'Underwater', 'Exploration'], descriptionKey: 'subnauticaDesc' },
    { name: 'Human: Fall Flat', appId: 477160, videoId: 'S_YQ_v-sX_A', tags: ['Physics', 'Puzzle', 'Co-op', 'Funny'], descriptionKey: 'humanFallFlatDesc' },
    { name: 'Euro Truck Simulator 2', appId: 227300, videoId: 'xlTuC18xVII', tags: ['Simulation', 'Driving', 'Relaxing', 'Open World'], descriptionKey: 'euroTruckSimulator2Desc' },
    { name: 'Cities: Skylines', appId: 255710, videoId: '0gI2N1Iejww', tags: ['City Builder', 'Simulation', 'Strategy', 'Management'], descriptionKey: 'citiesSkylinesDesc' },
    { name: "BioShock Remastered", appId: 409710, videoId: '9ewj-voN2fM', tags: ['FPS', 'Story Rich', 'Atmospheric'], descriptionKey: 'bioshockDesc' },
    { name: "The Sims 4", appId: 1222670, videoId: 'z_S0_z0b-G8', tags: ['Life Sim', 'Simulation', 'Character Customization'], descriptionKey: 'sims4Desc' },
    { name: "No Man's Sky", appId: 275850, videoId: 'v5-L_2-hG6s', tags: ['Open World', 'Survival', 'Space', 'Exploration'], descriptionKey: 'noMansSkyDesc' },
    { name: "Cuphead", appId: 268910, videoId: '3jDZfREYppk', tags: ['Difficult', '1930s Cartoon', 'Platformer', 'Co-op'], descriptionKey: 'cupheadDesc' },
    { name: "Dark Souls III", appId: 374320, videoId: 'f-M-g-a_f50', tags: ['Souls-like', 'Action RPG', 'Difficult', 'Dark Fantasy'], descriptionKey: 'darksouls3Desc' },
    { name: "Portal 2", appId: 620, videoId: 'AagpXIqlW-w', tags: ['Puzzle', 'Co-op', 'Sci-Fi', 'First-Person'], descriptionKey: 'portal2Desc' },
    { name: "Half-Life: Alyx", appId: 546560, videoId: 'O2W0N3u-pQ4', tags: ['VR', 'FPS', 'Action', 'Story Rich'], descriptionKey: 'alyxDesc' },
    { name: "Sekiro: Shadows Die Twice", appId: 814380, videoId: 'GRJ_pX3dZkE', tags: ['Action', 'Souls-like', 'Difficult', 'Ninja'], descriptionKey: 'sekiroDesc' },
    { name: "DOOM Eternal", appId: 782330, videoId: 'a_0-b3iV_gI', tags: ['FPS', 'Action', 'Demons', 'Fast-Paced'], descriptionKey: 'doomEternalDesc' },
    { name: "Control", appId: 870780, videoId: 'P4iA52K9fL8', tags: ['Action', 'Supernatural', 'Third Person', 'Metroidvania'], descriptionKey: 'controlDesc' },
    { name: "Deep Rock Galactic", appId: 548430, videoId: 'qhGxenbo4gE', tags: ['Co-op', 'FPS', 'Dwarves', 'Mining'], descriptionKey: 'deepRockGalacticDesc' },
    { name: "Satisfactory", appId: 526870, videoId: 'W_h2V_Atj6c', tags: ['Automation', 'Base Building', 'Open World', 'First-Person'], descriptionKey: 'satisfactoryDesc' },
    { name: "Fallout: New Vegas", appId: 22380, videoId: 'l-x-1KOPZ_A', tags: ['RPG', 'Open World', 'Post-Apocalyptic', 'Story Rich'], descriptionKey: 'falloutNewVegasDesc' },
    { name: "The Elder Scrolls IV: Oblivion", appId: 900883, videoId: 'hDb0I4o5R-U', tags: ['RPG', 'Open World', 'Fantasy', 'Classic'], descriptionKey: 'oblivionDesc' },
    { name: "Borderlands 2", appId: 49520, videoId: 'E_H-c3P7t8s', tags: ['Looter Shooter', 'FPS', 'Co-op', 'Action RPG'], descriptionKey: 'borderlands2Desc' },
    { name: "XCOM 2", appId: 268500, videoId: '3qLd4R12-pI', tags: ['Turn-Based Tactics', 'Strategy', 'Sci-Fi', 'Aliens'], descriptionKey: 'xcom2Desc' },
    { name: "Total War: WARHAMMER II", appId: 594570, videoId: 'fXxe89L_31M', tags: ['Strategy', 'RTS', 'Fantasy', 'Grand Strategy'], descriptionKey: 'totalWarhammer2Desc' },
    { name: "Stellaris", appId: 281990, videoId: 'zP9k_F_zABM', tags: ['Grand Strategy', '4X', 'Sci-Fi', 'Space'], descriptionKey: 'stellarisDesc' },
    { name: "Rocket League", appId: 252950, videoId: 'Om-k4g8F-wI', tags: ['Soccer', 'Sports', 'Multiplayer', 'Competitive'], descriptionKey: 'rocketLeagueDesc' },
    { name: "Path of Exile", appId: 238960, videoId: 'G-s-chrd0cI', tags: ['Action RPG', 'Hack and Slash', 'Free to Play', 'Loot'], descriptionKey: 'pathOfExileDesc' },
    { name: "War Thunder", appId: 236390, videoId: 'pzgO_o_k92k', tags: ['Vehicular Combat', 'WWII', 'Free to Play', 'Simulation'], descriptionKey: 'warThunderDesc' },
    // ADDING MORE GAMES (BATCH 3)!
    { name: "Mount & Blade II: Bannerlord", appId: 261550, videoId: 'hXvG7Jg21p0', tags: ['RPG', 'Strategy', 'Sandbox', 'Medieval'], descriptionKey: 'bannerlordDesc' },
    { name: "Crusader Kings III", appId: 1158310, videoId: 'xMy_t2I9T7U', tags: ['Grand Strategy', 'RPG', 'Medieval', 'Simulation'], descriptionKey: 'ck3Desc' },
    { name: "Divinity: Original Sin 2", appId: 435150, videoId: 'bTWT5_g2c1I', tags: ['CRPG', 'Turn-Based', 'Fantasy', 'Co-op'], descriptionKey: 'divinity2Desc' },
    { name: "Planet Zoo", appId: 703080, videoId: '1IGaB9tQo9w', tags: ['Simulation', 'Building', 'Management', 'Sandbox'], descriptionKey: 'planetZooDesc' },
    { name: "Frostpunk", appId: 323190, videoId: 'qqEpSOFDXGA', tags: ['City Builder', 'Survival', 'Strategy', 'Post-Apocalyptic'], descriptionKey: 'frostpunkDesc' },
    { name: "Celeste", appId: 504230, videoId: 'o_1-YZJ1T2A', tags: ['Platformer', 'Pixel Graphics', 'Indie', 'Difficult'], descriptionKey: 'celesteDesc' },
    { name: "Undertale", appId: 391540, videoId: '1Hojv0m3TqA', tags: ['RPG', 'Story Rich', 'Pixel Graphics', 'Indie'], descriptionKey: 'undertaleDesc' },
    { name: "Disco Elysium", appId: 632470, videoId: 'St_A_of43pY', tags: ['RPG', 'Detective', 'Story Rich', 'Noir'], descriptionKey: 'discoElysiumDesc' },
    { name: "Outer Wilds", appId: 753640, videoId: '4kYtnJ5vR3U', tags: ['Exploration', 'Mystery', 'Space', 'Puzzle'], descriptionKey: 'outerWildsDesc' },
    { name: "Risk of Rain 2", appId: 632360, videoId: 'a_yC0Qz_O8s', tags: ['Action Roguelike', 'Third-Person Shooter', 'Co-op', 'Looter Shooter'], descriptionKey: 'riskOfRain2Desc' }
];

const translations = {
    en: {
        // ... (existing descriptions) ...
        bannerlordDesc: "The horns sound, the ravens gather. An empire is torn by civil war. Beyond its borders, new kingdoms rise. Gird on your sword, don your armour, summon your followers and ride forth to win glory on the battlefields of Calradia. Establish your hegemony and create a new world out of the ashes of the old.",
        ck3Desc: "Love, fight, scheme, and claim greatness. Determine your noble house’s legacy in the sprawling grand strategy of Crusader Kings III. Death is only the beginning as you guide your dynasty’s lineage in the rich and larger-than-life simulation of the Middle Ages.",
        divinity2Desc: "The critically acclaimed RPG that raised the bar, from the creators of Baldur's Gate 3. Master deep, tactical combat. Venture as a party of up to four - but know that only one of you will have the chance to become a God.",
        planetZooDesc: "Build a world for wildlife in Planet Zoo. From the developers of Planet Coaster and Zoo Tycoon comes the ultimate zoo sim. Construct detailed habitats, manage your zoo, and meet authentic living animals who think, feel and explore the world you create around them.",
        frostpunkDesc: "Frostpunk is the first society survival game. As the ruler of the last city on Earth, it is your duty to manage both its citizens and its infrastructure. What decisions will you make to ensure your society's survival? What will you do when pushed to the limit?",
        celesteDesc: "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight, hand-crafted platformer from the creators of TowerFall.",
        undertaleDesc: "UNDERTALE! The RPG game where you don't have to destroy anyone.",
        discoElysiumDesc: "Disco Elysium - The Final Cut is a groundbreaking role playing game. You’re a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters, crack murders or take bribes.",
        outerWildsDesc: "Named Game of the Year 2019 by Giant Bomb, Polygon, Eurogamer, and The Guardian, Outer Wilds is a critically-acclaimed and award-winning open world mystery about a solar system trapped in an endless time loop.",
        riskOfRain2Desc: "Escape a chaotic alien planet by fighting through hordes of frenzied monsters – with your friends, or on your own. Combine loot in surprising ways and master each character until you become the havoc you feared upon your first crash landing."
    },
    ko: {
        // ... (existing descriptions) ...
        bannerlordDesc: "뿔나팔 소리가 울리고 까마귀들이 모여듭니다. 제국은 내전으로 찢어졌습니다. 국경 너머에는 새로운 왕국이 세워집니다. 칼을 차고 갑옷을 입고 추종자들을 소환하여 칼라디아의 전장에서 영광을 쟁취하기 위해 말을 타십시오. 패권을 확립하고 낡은 것의 잿더미에서 새로운 세계를 만드십시오.",
        ck3Desc: "사랑하고, 싸우고, 계략을 꾸미고, 위대함을 주장하십시오. Crusader Kings III의 광활한 대전략에서 당신의 귀족 가문의 유산을 결정하십시오. 죽음은 중세의 풍부하고 실제보다 더 큰 시뮬레이션에서 왕조의 혈통을 안내하는 시작에 불과합니다.",
        divinity2Desc: "Baldur's Gate 3의 제작진이 만든, 기준을 높인 비평가들의 극찬을 받은 RPG. 깊이 있고 전술적인 전투를 마스터하십시오. 최대 4명의 파티로 모험을 떠나십시오. 하지만 오직 한 명만이 신이 될 기회를 갖게 될 것임을 알아두십시오.",
        planetZooDesc: "Planet Zoo에서 야생 동물을 위한 세계를 건설하세요. Planet Coaster 및 Zoo Tycoon의 개발자가 만든 최고의 동물원 시뮬레이션입니다. 상세한 서식지를 건설하고, 동물원을 관리하고, 주변에 만든 세상을 생각하고, 느끼고, 탐험하는 실제 살아있는 동물을 만나보세요.",
        frostpunkDesc: "Frostpunk는 최초의 사회 생존 게임입니다. 지구상 마지막 도시의 통치자로서 시민과 기반 시설을 모두 관리하는 것이 당신의 의무입니다. 사회의 생존을 보장하기 위해 어떤 결정을 내리시겠습니까? 한계에 부딪혔을 때 당신은 무엇을 할 것입니까?",
        celesteDesc: "TowerFall 제작진이 만든 이 매우 타이트하고 수작업으로 제작된 플랫폼 게임에서 Madeline이 Celeste 산 정상으로 가는 여정에서 내면의 악마를 이겨내도록 도와주세요.",
        undertaleDesc: "UNDERTALE! 아무도 파괴할 필요가 없는 RPG 게임입니다.",
        discoElysiumDesc: "Disco Elysium - The Final Cut은 획기적인 롤플레잉 게임입니다. 당신은 독특한 기술 시스템을 마음대로 사용할 수 있는 형사이며, 길을 개척할 도시 구역 전체가 있습니다. 잊을 수 없는 캐릭터를 심문하고, 살인 사건을 해결하거나, 뇌물을 받으십시오.",
        outerWildsDesc: "Giant Bomb, Polygon, Eurogamer, The Guardian에서 2019년 올해의 게임으로 선정된 Outer Wilds는 끝없는 시간 루프에 갇힌 태양계에 대한 비평가들의 극찬을 받고 수상 경력에 빛나는 오픈 월드 미스터리입니다.",
        riskOfRain2Desc: "친구와 함께 또는 혼자서 광란의 괴물 무리를 헤치고 싸워 혼돈의 외계 행성에서 탈출하십시오. 놀라운 방식으로 전리품을 결합하고 첫 번째 추락 착륙 시 두려워했던 대혼란이 될 때까지 각 캐릭터를 마스터하십시오."
    }
}
